/**
 * SQAD-Public Context File Generator
 *
 * Generates CONTEXT.md (canonical) and IDE-specific copies
 * (CLAUDE.md, GEMINI.md, AGENTS.md, etc.) from config and workspace scan.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { readConfig } from './config.js';

/**
 * Generate context files for the workspace.
 * @param {string} workspacePath - Absolute path to workspace root
 * @param {object} options - Generation options
 * @param {boolean} [options.force=false] - Overwrite existing files
 * @returns {{ generated: string[], skipped: string[] }}
 */
export function generateContextFiles(workspacePath, options = {}) {
  const methodDir = join(workspacePath, 'sqad-method');
  const configPath = join(methodDir, 'config.yaml');
  const config = readConfig(configPath) || {};

  const result = { generated: [], skipped: [] };

  // Build CONTEXT.md content
  const contextContent = buildContextContent(workspacePath, config);

  // Write canonical CONTEXT.md
  const contextPath = join(workspacePath, 'CONTEXT.md');
  if (!existsSync(contextPath) || options.force) {
    writeFileSync(contextPath, contextContent, 'utf8');
    result.generated.push('CONTEXT.md');
  } else {
    result.skipped.push('CONTEXT.md (exists — use --force to overwrite)');
  }

  // Write IDE copies based on config
  const copies = config.context_files?.copies || ['CLAUDE.md', 'GEMINI.md', 'AGENTS.md'];
  for (const copyName of copies) {
    const copyPath = join(workspacePath, copyName);
    if (!existsSync(copyPath) || options.force) {
      writeFileSync(copyPath, contextContent, 'utf8');
      result.generated.push(copyName);
    } else {
      result.skipped.push(`${copyName} (exists)`);
    }
  }

  return result;
}

/**
 * Build the CONTEXT.md content from config and workspace scan.
 */
function buildContextContent(workspacePath, config) {
  const date = new Date().toISOString().split('T')[0];
  const userName = config.user?.name || '{{user_name}}';
  const userRole = config.user?.role || '{{user_role}}';
  const teamName = config.team?.name || '{{team_name}}';
  const companyName = config.company?.name || '{{company_name}}';
  const projectName = config.project?.name || '{{project_name}}';
  const projectDesc = config.project?.description || '{{project_description}}';
  const languages = config.stack?.languages || [];
  const frameworks = config.stack?.frameworks || [];
  const testFrameworks = config.stack?.test_frameworks || [];
  const providers = config.cloud?.providers || [];
  const iac = config.cloud?.iac || [];
  const ciCd = config.cloud?.ci_cd || [];
  const container = config.cloud?.container || [];
  const trackerType = config.tracker?.type || 'none';
  const githubHost = config.github?.host || 'github.com';
  const githubOrg = config.github?.org || '';
  const defaultBranch = config.github?.default_branch || 'main';

  // Scan for repos
  const repos = scanRepos(workspacePath);

  // Scan for non-git dirs
  const nonGitDirs = scanNonGitDirs(workspacePath);

  let md = `<!-- SQAD:auto-generated by /refresh on ${date} -->
# ${projectName || basename(workspacePath)}

## Identity
Team: ${teamName} | User: ${userName} (${userRole})
Company: ${companyName}
Stack: ${languages.join(', ') || 'not detected'} | ${frameworks.join(', ') || 'no frameworks'}
Cloud: ${providers.join(', ') || 'none'} (${iac.join(', ') || 'no IaC'})
CI/CD: ${ciCd.join(', ') || 'none'}
Tracker: ${trackerType}
GitHub: ${githubHost}/${githubOrg} (branch: ${defaultBranch})

## IMPORTANT: Rules
1. All tests must pass before story completion
2. TDD: tests first, then implementation
3. ${trackerType !== 'none' ? trackerType + ' is source of truth for stories/sprints' : 'Configure a tracker in config.yaml for story tracking'}
4. User confirms at every phase gate
5. NEVER fabricate data — if uncertain, ASK
6. Use project stack (${languages.join(', ')}) unless told otherwise
7. Tag all assumptions [ASSUMPTION-N] for verification
8. Minimal, surgical changes following existing patterns
9. Search ALL repos for shared infra before creating new
10. Follow existing code patterns — consistency > novelty
`;

  // Repository Map
  if (repos.length > 0) {
    md += `\n## Repository Map\n\n`;
    md += `| Repo | Type | Key Files | Tests |\n|---|---|---|---|\n`;
    for (const repo of repos) {
      md += `| ${repo.name} | ${repo.type} | ${repo.keyFiles} | ${repo.testInfo} |\n`;
    }
  }

  // Build commands
  const testCmd = config.stack?.test_command || '';
  const buildCmd = config.stack?.build_command || '';
  const lintCmd = config.stack?.lint_command || '';
  if (testCmd || buildCmd || lintCmd) {
    md += `\n## Build\n`;
    if (testCmd) md += `Test: \`${testCmd}\`\n`;
    if (buildCmd) md += `Build: \`${buildCmd}\`\n`;
    if (lintCmd) md += `Lint: \`${lintCmd}\`\n`;
  }

  // Non-git workspace contents
  if (nonGitDirs.length > 0) {
    md += `\n## Other Workspace Contents\n\n`;
    md += `| Directory | What It Is | Items |\n|---|---|---|\n`;
    for (const dir of nonGitDirs) {
      md += `| ${dir.name}/ | ${dir.description} | ${dir.count} |\n`;
    }
  }

  md += `\n## Knowledge Graph\n`;
  md += `<!-- Populated by /refresh if knowledge_graph.enabled is true -->\n`;
  md += `Run /refresh to build knowledge graphs and populate this section.\n`;

  md += `\n## SQAD-Public\n`;
  md += `14 agents · 25 commands · sqad-method/ for config\n`;

  return md;
}

/**
 * Scan for git repos in workspace (1 level deep).
 */
function scanRepos(workspacePath) {
  const repos = [];
  try {
    const entries = readdirSync(workspacePath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
      const repoDir = join(workspacePath, entry.name);
      if (existsSync(join(repoDir, '.git'))) {
        repos.push({
          name: entry.name,
          type: detectRepoType(repoDir),
          keyFiles: countKeyFiles(repoDir),
          testInfo: detectTestInfo(repoDir),
        });
      }
    }
  } catch (e) { /* ignore */ }
  return repos;
}

/**
 * Scan for non-git directories at workspace root.
 */
function scanNonGitDirs(workspacePath) {
  const dirs = [];
  try {
    const entries = readdirSync(workspacePath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
      const dirPath = join(workspacePath, entry.name);
      if (!existsSync(join(dirPath, '.git'))) {
        const count = countFilesRecursive(dirPath);
        dirs.push({
          name: entry.name,
          description: describeDir(dirPath, entry.name),
          count,
        });
      }
    }
  } catch (e) { /* ignore */ }
  return dirs;
}

/**
 * Detect repo type from marker files.
 */
function detectRepoType(repoDir) {
  if (existsSync(join(repoDir, 'package.json'))) {
    try {
      const pkg = JSON.parse(readFileSync(join(repoDir, 'package.json'), 'utf8'));
      if (pkg.dependencies?.next || pkg.devDependencies?.next) return 'Next.js';
      if (pkg.dependencies?.react || pkg.devDependencies?.react) return 'React';
      if (pkg.dependencies?.express) return 'Express';
      return 'Node.js';
    } catch (e) { return 'Node.js'; }
  }
  if (existsSync(join(repoDir, 'pyproject.toml')) || existsSync(join(repoDir, 'requirements.txt'))) return 'Python';
  if (existsSync(join(repoDir, 'go.mod'))) return 'Go';
  if (existsSync(join(repoDir, 'Cargo.toml'))) return 'Rust';
  if (existsSync(join(repoDir, 'pom.xml'))) return 'Java/Maven';
  if (existsSync(join(repoDir, 'Gemfile'))) return 'Ruby';
  return 'Unknown';
}

/**
 * Count key source files in a repo.
 */
function countKeyFiles(repoDir) {
  try {
    const srcDir = join(repoDir, 'src');
    if (existsSync(srcDir)) {
      return `src/ present`;
    }
    const libDir = join(repoDir, 'lib');
    if (existsSync(libDir)) {
      return `lib/ present`;
    }
    return 'flat structure';
  } catch (e) { return 'unknown'; }
}

/**
 * Detect test info in a repo.
 */
function detectTestInfo(repoDir) {
  const testDirs = ['test', 'tests', '__tests__', 'spec'];
  for (const dir of testDirs) {
    if (existsSync(join(repoDir, dir))) return `${dir}/ present`;
  }
  if (existsSync(join(repoDir, 'src', 'test'))) return 'src/test/ present';
  return 'no tests detected';
}

/**
 * Count files recursively (limited depth).
 */
function countFilesRecursive(dir, depth = 0, maxDepth = 3) {
  if (depth > maxDepth) return 0;
  let count = 0;
  try {
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
      if (entry.isFile()) count++;
      else if (entry.isDirectory()) count += countFilesRecursive(join(dir, entry.name), depth + 1, maxDepth);
    }
  } catch (e) { /* ignore */ }
  return count;
}

/**
 * Describe a non-git directory from its name or README.
 */
function describeDir(dirPath, name) {
  // Check for README
  const readmePath = join(dirPath, 'README.md');
  if (existsSync(readmePath)) {
    try {
      const first = readFileSync(readmePath, 'utf8').split('\n').find(l => l.trim() && !l.startsWith('#'));
      if (first) return first.trim().slice(0, 60);
    } catch (e) { /* ignore */ }
  }
  // Infer from name
  const descriptions = {
    'sqad-method': 'SQAD-Public framework config',
    'docs': 'Documentation',
    'scripts': 'Build/deploy scripts',
    'config': 'Configuration files',
    'dist': 'Build output',
    'build': 'Build output',
    'public': 'Static assets',
    'assets': 'Static assets',
  };
  return descriptions[name] || `${name} directory`;
}
