/**
 * SQUAD-Public Context File Generator
 *
 * Generates CONTEXT.md (canonical) and IDE-specific copies
 * (CLAUDE.md, GEMINI.md, AGENTS.md, etc.) from config and workspace scan.
 */

import { existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync } from 'node:fs';
import { join, basename } from 'node:path';
import { readConfig } from './config.js';

/**
 * Generate context files for the workspace.
 * @param {string} workspacePath - Absolute path to workspace root
 * @param {object} options - Generation options
 * @param {boolean} [options.force=false] - Overwrite existing files
 * @param {Array<{name: string, path: string}>} [options.repos=[]] - Detected repos
 * @returns {{ generated: string[], skipped: string[] }}
 */
export function generateContextFiles(workspacePath, options = {}) {
  const methodDir = join(workspacePath, 'squad-method');
  // Try squad.yaml first (new canonical name), fall back to config.yaml (legacy)
  const squadYamlPath = join(methodDir, 'squad.yaml');
  const configYamlPath = join(methodDir, 'config.yaml');
  const configPath = existsSync(squadYamlPath) ? squadYamlPath : configYamlPath;
  const config = readConfig(configPath) || {};

  const result = { generated: [], skipped: [] };

  // Build root CONTEXT.md content
  const contextContent = buildContextContent(workspacePath, config);

  // Write canonical CONTEXT.md
  const contextPath = join(workspacePath, 'CONTEXT.md');
  if (!existsSync(contextPath) || options.force) {
    writeFileSync(contextPath, contextContent, 'utf8');
    result.generated.push('CONTEXT.md');
  } else {
    result.skipped.push('CONTEXT.md (exists — use --force to overwrite)');
  }

  // Write IDE copies based on config
  const copies = config.context_files?.copies || ['CLAUDE.md', 'GEMINI.md', 'AGENTS.md'];
  for (const copyName of copies) {
    const copyPath = join(workspacePath, copyName);
    if (!existsSync(copyPath) || options.force) {
      writeFileSync(copyPath, contextContent, 'utf8');
      result.generated.push(copyName);
    } else {
      result.skipped.push(`${copyName} (exists)`);
    }
  }

  // Generate per-repo context files
  const repos = options.repos || [];
  for (const repo of repos) {
    const repoContent = buildRepoContextContent(repo, workspacePath, config);
    for (const name of ['CLAUDE.md', 'CONTEXT.md']) {
      const repoCtxPath = join(repo.path, name);
      if (!existsSync(repoCtxPath) || options.force) {
        writeFileSync(repoCtxPath, repoContent, 'utf8');
        result.generated.push(`${repo.name}/${name}`);
      } else {
        result.skipped.push(`${repo.name}/${name} (exists)`);
      }
    }
  }

  // Single-repo workspace — generate inside repo root if it's also workspace root
  if (repos.length === 0 && existsSync(join(workspacePath, '.git'))) {
    // Already wrote root-level files; also create DEEP-CONTEXT.md
    const deepContent = buildDeepContextContent(workspacePath, config);
    const deepPath = join(workspacePath, 'DEEP-CONTEXT.md');
    if (!existsSync(deepPath) || options.force) {
      writeFileSync(deepPath, deepContent, 'utf8');
      result.generated.push('DEEP-CONTEXT.md');
    } else {
      result.skipped.push('DEEP-CONTEXT.md (exists)');
    }
  }

  return result;
}

/**
 * Build the CONTEXT.md content from config and workspace scan.
 */
function buildContextContent(workspacePath, config) {
  const date = new Date().toISOString().split('T')[0];
  const userName = config.user?.name || '{{user_name}}';
  const userRole = config.user?.role || '{{user_role}}';
  const teamName = config.team?.name || '{{team_name}}';
  const companyName = config.company?.name || '{{company_name}}';
  const projectName = config.project?.name || '{{project_name}}';
  const projectDesc = config.project?.description || '{{project_description}}';
  const languages = config.stack?.languages || [];
  const frameworks = config.stack?.frameworks || [];
  const testFrameworks = config.stack?.test_frameworks || [];
  const providers = config.cloud?.providers || [];
  const iac = config.cloud?.iac || [];
  const ciCd = config.cloud?.ci_cd || [];
  const container = config.cloud?.container || [];
  const trackerType = config.tracker?.type || 'none';
  const githubHost = config.github?.host || 'github.com';
  const githubOrg = config.github?.org || '';
  const defaultBranch = config.github?.default_branch || 'main';

  // Scan for repos
  const repos = scanRepos(workspacePath);

  // Scan for non-git dirs
  const nonGitDirs = scanNonGitDirs(workspacePath);

  let md = `<!-- SQUAD:auto-generated by /refresh on ${date} -->
# ${projectName || basename(workspacePath)}

## Identity
Team: ${teamName} | User: ${userName} (${userRole})
Company: ${companyName}
Stack: ${languages.join(', ') || 'not detected'} | ${frameworks.join(', ') || 'no frameworks'}
Cloud: ${providers.join(', ') || 'none'} (${iac.join(', ') || 'no IaC'})
CI/CD: ${ciCd.join(', ') || 'none'}
Tracker: ${trackerType}
GitHub: ${githubHost}/${githubOrg} (branch: ${defaultBranch})

## IMPORTANT: Rules
1. All tests must pass before story completion
2. TDD: tests first, then implementation
3. ${trackerType !== 'none' ? trackerType + ' is source of truth for stories/sprints' : 'Configure a tracker in config.yaml for story tracking'}
4. User confirms at every phase gate
5. NEVER fabricate data — if uncertain, ASK
6. Use project stack (${languages.join(', ')}) unless told otherwise
7. Tag all assumptions [ASSUMPTION-N] for verification
8. Minimal, surgical changes following existing patterns
9. Search ALL repos for shared infra before creating new
10. Follow existing code patterns — consistency > novelty
`;

  // Repository Map
  if (repos.length > 0) {
    md += `\n## Repository Map\n\n`;
    md += `| Repo | Type | Key Files | Tests |\n|---|---|---|---|\n`;
    for (const repo of repos) {
      md += `| ${repo.name} | ${repo.type} | ${repo.keyFiles} | ${repo.testInfo} |\n`;
    }
  }

  // Build commands
  const testCmd = config.stack?.test_command || '';
  const buildCmd = config.stack?.build_command || '';
  const lintCmd = config.stack?.lint_command || '';
  if (testCmd || buildCmd || lintCmd) {
    md += `\n## Build\n`;
    if (testCmd) md += `Test: \`${testCmd}\`\n`;
    if (buildCmd) md += `Build: \`${buildCmd}\`\n`;
    if (lintCmd) md += `Lint: \`${lintCmd}\`\n`;
  }

  // Non-git workspace contents
  if (nonGitDirs.length > 0) {
    md += `\n## Other Workspace Contents\n\n`;
    md += `| Directory | What It Is | Items |\n|---|---|---|\n`;
    for (const dir of nonGitDirs) {
      md += `| ${dir.name}/ | ${dir.description} | ${dir.count} |\n`;
    }
  }

  md += `\n## Knowledge Graph\n`;
  md += `<!-- Populated by /refresh if knowledge_graph.enabled is true -->\n`;
  md += `Run /refresh to build knowledge graphs and populate this section.\n`;

  md += `\n## SQUAD-Public\n`;
  md += `26 agents · 29 skills · squad-method/ for config\n`;

  return md;
}

/**
 * Scan for git repos in workspace (1 level deep).
 */
function scanRepos(workspacePath) {
  const repos = [];
  try {
    const entries = readdirSync(workspacePath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
      const repoDir = join(workspacePath, entry.name);
      if (existsSync(join(repoDir, '.git'))) {
        repos.push({
          name: entry.name,
          type: detectRepoType(repoDir),
          keyFiles: countKeyFiles(repoDir),
          testInfo: detectTestInfo(repoDir),
        });
      }
    }
  } catch (e) { /* ignore */ }
  return repos;
}

/**
 * Scan for non-git directories at workspace root.
 */
function scanNonGitDirs(workspacePath) {
  const dirs = [];
  try {
    const entries = readdirSync(workspacePath, { withFileTypes: true });
    for (const entry of entries) {
      if (!entry.isDirectory()) continue;
      if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
      const dirPath = join(workspacePath, entry.name);
      if (!existsSync(join(dirPath, '.git'))) {
        const count = countFilesRecursive(dirPath);
        dirs.push({
          name: entry.name,
          description: describeDir(dirPath, entry.name),
          count,
        });
      }
    }
  } catch (e) { /* ignore */ }
  return dirs;
}

/**
 * Detect repo type from marker files.
 */
function detectRepoType(repoDir) {
  if (existsSync(join(repoDir, 'package.json'))) {
    try {
      const pkg = JSON.parse(readFileSync(join(repoDir, 'package.json'), 'utf8'));
      if (pkg.dependencies?.next || pkg.devDependencies?.next) return 'Next.js';
      if (pkg.dependencies?.react || pkg.devDependencies?.react) return 'React';
      if (pkg.dependencies?.express) return 'Express';
      return 'Node.js';
    } catch (e) { return 'Node.js'; }
  }
  if (existsSync(join(repoDir, 'pyproject.toml')) || existsSync(join(repoDir, 'requirements.txt'))) return 'Python';
  if (existsSync(join(repoDir, 'go.mod'))) return 'Go';
  if (existsSync(join(repoDir, 'Cargo.toml'))) return 'Rust';
  if (existsSync(join(repoDir, 'pom.xml'))) return 'Java/Maven';
  if (existsSync(join(repoDir, 'Gemfile'))) return 'Ruby';
  return 'Unknown';
}

/**
 * Count key source files in a repo.
 */
function countKeyFiles(repoDir) {
  try {
    const srcDir = join(repoDir, 'src');
    if (existsSync(srcDir)) {
      return `src/ present`;
    }
    const libDir = join(repoDir, 'lib');
    if (existsSync(libDir)) {
      return `lib/ present`;
    }
    return 'flat structure';
  } catch (e) { return 'unknown'; }
}

/**
 * Detect test info in a repo.
 */
function detectTestInfo(repoDir) {
  const testDirs = ['test', 'tests', '__tests__', 'spec'];
  for (const dir of testDirs) {
    if (existsSync(join(repoDir, dir))) return `${dir}/ present`;
  }
  if (existsSync(join(repoDir, 'src', 'test'))) return 'src/test/ present';
  return 'no tests detected';
}

/**
 * Count files recursively (limited depth).
 */
function countFilesRecursive(dir, depth = 0, maxDepth = 3) {
  if (depth > maxDepth) return 0;
  let count = 0;
  try {
    const entries = readdirSync(dir, { withFileTypes: true });
    for (const entry of entries) {
      if (entry.name.startsWith('.') || entry.name === 'node_modules') continue;
      if (entry.isFile()) count++;
      else if (entry.isDirectory()) count += countFilesRecursive(join(dir, entry.name), depth + 1, maxDepth);
    }
  } catch (e) { /* ignore */ }
  return count;
}

/**
 * Describe a non-git directory from its name or README.
 */
function describeDir(dirPath, name) {
  // Check for README
  const readmePath = join(dirPath, 'README.md');
  if (existsSync(readmePath)) {
    try {
      const first = readFileSync(readmePath, 'utf8').split('\n').find(l => l.trim() && !l.startsWith('#'));
      if (first) return first.trim().slice(0, 60);
    } catch (e) { /* ignore */ }
  }
  // Infer from name
  const descriptions = {
    'squad-method': 'SQUAD-Public framework config',
    'docs': 'Documentation',
    'scripts': 'Build/deploy scripts',
    'config': 'Configuration files',
    'dist': 'Build output',
    'build': 'Build output',
    'public': 'Static assets',
    'assets': 'Static assets',
  };
  return descriptions[name] || `${name} directory`;
}

/**
 * Build per-repo CLAUDE.md/CONTEXT.md content with KG data + repo-specific info.
 *
 * graph.json schema (from squad-method/tools/knowledge-graph/index.js):
 *   nodes: [{ id, type, label, file, line, confidence }]
 *   edges: [{ source, target, type }]
 *   stats: { nodes, edges }
 */
function buildRepoContextContent(repo, workspacePath, config) {
  const date = new Date().toISOString().split('T')[0];
  const repoType = detectRepoType(repo.path);
  const testInfo = detectTestInfo(repo.path);

  let md = `<!-- SQUAD:auto-generated per-repo context on ${date} -->\n`;
  md += `# ${repo.name}\n\n`;
  md += `**Type:** ${repoType} | **Tests:** ${testInfo}\n`;
  md += `**Workspace:** ${basename(workspacePath)}\n`;
  md += `**SQUAD Config:** ../squad-method/config.yaml\n\n`;

  // Include KG summary if graph.json exists
  const graphPath = join(repo.path, 'knowledge-graph-out', 'graph.json');
  if (existsSync(graphPath)) {
    try {
      const graph = JSON.parse(readFileSync(graphPath, 'utf8'));
      const nodes = graph.nodes || [];
      const edges = graph.edges || [];

      // Compute degree map (in + out edges per node id)
      const degreeMap = new Map();
      for (const e of edges) {
        degreeMap.set(e.source, (degreeMap.get(e.source) || 0) + 1);
        degreeMap.set(e.target, (degreeMap.get(e.target) || 0) + 1);
      }

      // Classify test vs source nodes
      const isTestNode = (n) => {
        if (n.type === 'test' || n.type === 'test_file') return true;
        const id = n.id || n.file || '';
        return /test|spec|__tests__/.test(id);
      };

      const sourceNodes = nodes.filter(n => !isTestNode(n));
      const testNodes = nodes.filter(n => isTestNode(n));

      // God nodes (degree > 30)
      const godNodes = nodes.filter(n => (degreeMap.get(n.id) || 0) > 30);

      md += `## Knowledge Graph\n\n`;
      md += `Nodes: ${graph.stats?.nodes || nodes.length} | Edges: ${graph.stats?.edges || edges.length} | `;
      md += `Source: ${sourceNodes.length} | Tests: ${testNodes.length} | `;
      md += `God nodes: ${godNodes.length}\n\n`;

      // God nodes table
      if (godNodes.length > 0) {
        md += `### God Nodes (degree > 30) — EXTRA CARE REQUIRED\n\n`;
        md += `| File | Degree | Type |\n|---|---|---|\n`;
        for (const n of godNodes.sort((a, b) => (degreeMap.get(b.id) || 0) - (degreeMap.get(a.id) || 0)).slice(0, 10)) {
          md += `| ${n.id} | ${degreeMap.get(n.id) || 0} | ${n.type || 'unknown'} |\n`;
        }
        md += `\n`;
      }

      // Highest coupling (top 8 by degree)
      const rankedNodes = [...nodes].sort((a, b) => (degreeMap.get(b.id) || 0) - (degreeMap.get(a.id) || 0)).slice(0, 8);
      if (rankedNodes.length > 0) {
        md += `### Highest Coupling\n\n`;
        md += `| File | Degree | Test Coverage |\n|---|---|---|\n`;
        for (const n of rankedNodes) {
          const degree = degreeMap.get(n.id) || 0;
          const testCount = edges.filter(e => e.target === n.id && e.type === 'tests').length;
          md += `| ${n.id} | ${degree} | ${testCount > 0 ? testCount + ' tests' : '⚠️ UNTESTED'} |\n`;
        }
        md += `\n`;
      }

      // Untested source files
      const testedIds = new Set(edges.filter(e => e.type === 'tests').map(e => e.target));
      const untested = sourceNodes.filter(n => !testedIds.has(n.id));
      if (untested.length > 0) {
        md += `### Untested Files (${untested.length}/${sourceNodes.length})\n\n`;
        const sorted = untested.sort((a, b) => (degreeMap.get(b.id) || 0) - (degreeMap.get(a.id) || 0));
        for (const n of sorted.slice(0, 10)) {
          md += `- ${n.id} (degree ${degreeMap.get(n.id) || 0})\n`;
        }
        if (untested.length > 10) md += `- ... and ${untested.length - 10} more\n`;
        md += `\n`;
      }

      // Communities (if present in graph output)
      if (graph.communities && graph.communities.length > 1) {
        md += `### Communities (${graph.communities.length})\n\n`;
        const sorted = [...graph.communities].sort((a, b) => (b.size || b.members?.length || 0) - (a.size || a.members?.length || 0));
        for (const c of sorted.slice(0, 8)) {
          const size = c.size || c.members?.length || 0;
          const key = c.keyNode || c.key || c.id || '';
          md += `- **${c.id || c.name}**: ${size} files (key: ${key})\n`;
        }
        md += `\n`;
      }
    } catch (e) { /* skip on parse error */ }
  } else {
    md += `## Knowledge Graph\n\nNot yet built. Run \`node squad-method/tools/knowledge-graph/build.js ${repo.name}\` to generate.\n\n`;
  }

  // KG report summary if exists
  const reportPath = join(repo.path, 'knowledge-graph-out', 'KG_REPORT.md');
  if (existsSync(reportPath)) {
    md += `> Full KG report: \`${repo.name}/knowledge-graph-out/KG_REPORT.md\`\n`;
    md += `> Interactive graph: \`${repo.name}/knowledge-graph-out/graph.html\`\n\n`;
  }

  md += `## Agent Instructions\n\n`;
  md += `When working in this repo:\n`;
  md += `1. **Read \`knowledge-graph-out/graph.json\` BEFORE grepping** — it has pre-computed dependency data\n`;
  md += `2. Query reverse dependencies for any file you plan to change\n`;
  md += `3. Check god nodes — changes to high-degree files need user approval\n`;
  md += `4. Check untested files — add tests before modifying untested code\n`;
  md += `5. Reference \`../CONTEXT.md\` for workspace-wide context\n`;

  return md;
}

/**
 * Build DEEP-CONTEXT.md for single-repo workspaces.
 */
function buildDeepContextContent(workspacePath, config) {
  const date = new Date().toISOString().split('T')[0];
  const repoName = basename(workspacePath);

  let md = `<!-- SQUAD:auto-generated deep context on ${date} -->\n`;
  md += `# Deep Context — ${repoName}\n\n`;

  // KG summary
  const graphPath = join(workspacePath, 'knowledge-graph-out', 'graph.json');
  if (existsSync(graphPath)) {
    try {
      const graph = JSON.parse(readFileSync(graphPath, 'utf8'));
      const nodes = graph.nodes || [];
      const edges = graph.edges || [];

      // Compute degree + classify
      const degreeMap = new Map();
      for (const e of edges) {
        degreeMap.set(e.source, (degreeMap.get(e.source) || 0) + 1);
        degreeMap.set(e.target, (degreeMap.get(e.target) || 0) + 1);
      }
      const isTest = (n) => n.type === 'test' || n.type === 'test_file' || /test|spec|__tests__/.test(n.id || '');
      const sourceCount = nodes.filter(n => !isTest(n)).length;
      const testCount = nodes.filter(n => isTest(n)).length;
      const godCount = nodes.filter(n => (degreeMap.get(n.id) || 0) > 30).length;

      md += `## Architecture (from Knowledge Graph)\n\n`;
      md += `- **${nodes.length} modules**, ${edges.length} dependency edges\n`;
      md += `- **${sourceCount} source**, ${testCount} test files\n`;
      md += `- **${godCount} god nodes** (degree > 30)\n\n`;

      if (graph.communities?.length > 0) {
        md += `### Module Communities\n\n`;
        const sorted = [...graph.communities].sort((a, b) => (b.size || 0) - (a.size || 0));
        for (const c of sorted.slice(0, 10)) {
          md += `- **${c.id || c.name}**: ${c.size || c.members?.length || 0} files\n`;
        }
        md += `\n`;
      }
    } catch (e) { /* skip */ }
  }

  md += `## Configuration\n\n`;
  md += `See \`squad-method/config.yaml\` for detected stack, cloud, and tracker.\n`;

  return md;
}
